### ISSUE TITLE
[Enhancement proposal] Cross plattform shell menu support

### ISSUE THREAD

**Issue by strarsis** [peteward44/node-win32shellmenu#2]
It would be great if this module could manage shell menus on popular platforms (OS X, Linux (Desktops)), exposed through a consistent API.

Thanks and 
with best regards

**Comment by peteward44** [comment]
Nice idea but that's a pretty big project in itself, something i don't have the time for myself. However, I would support someone willing to do this, using node-win32shellmenu for the windows part of the project.
